language: ruby
rvm:
  - 2.3.0
script: 
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test rake db:migrate
  - bundle exec rspec

# deploy:
#   provider: heroku
#   api_key: ENV['HEROKU_API']  
#   on: master
#   run: "rake db:migrate"
